kaiachain/kips

KIPs/kip-163.md

Update max commission rate to 100%.

Update max commission rate

---

KIPs/kip-226.md

Fix the wrong header field for `kip` in KIP-226. 

Fix wrong kip number

---

KIPs/kip-228.md

- Add the missing clauses about CodeInfo field.

kip-228: SetCodeTx updates CodeInfo as well

---

KIPs/kip-226.md

This PR adds:
- Json-rpc section
- Reset lockup period for CL staking
- Add discussion-to

Update kip 226

---

KIPs/kip-201.md

- Describe your changes to communicate to the maintainers why we should accept this pull request.
- If it fixes a bug or resolves a feature request, be sure to link to that issue.

KIP-201: KIP Process Upgrade

---

KIPs/kip-237.md

Fix header table of kip-237

---

index.html

Uppdate the legacy KIP-1 to KIP-201 for the welcome page.

Use KIP-201 for welcome page

---

KIPs/kip-201.md

Update the KIP-201 as `Active` status.

Update kip-201 status to Active

---

KIPs/kip-1.md
KIPs/kip-226.md

Update outdated contents

---

KIPs/kip-245.md

[KIP-245] Transaction Bundle

---

KIPs/kip-249.md

Please note that this PR doesn't change any contents of KIP-249, but only tidy up the markdown.

[KIP-249] Tidy up

---

KIPs/kip-247.md

I added an explanation of the GaslessSwapRouter contract interface.

KIP-247: Add explanation about the GaslessSwapRouter contract interface

---

_data/statuses.yaml
index.html

Add missing KIP status

---

KIPs/kip-245.md

Remove conflict handling statements. Promote KIP to review stage.

KIP-245: Review stage

---

KIPs/kip-247.md

KIP-247: Review stage

---

KIPs/kip-245.md

Sync with the latest implementation of core

KIP-245: sync kip-245 with latest impl

---

KIPs/kip-247.md

KIP-247: Add acceptable tokens

---

KIPs/kip-249.md

This PR reflects updates on KIP-249.

Improve KIP249

---

KIPs/kip-249.md

Finalized exposed API interface.

[KIP-249] Exposed API finalized

---

KIPs/kip-249.md

[KIP-249] Added missing api

---

KIPs/kip-223.md

- Kaia Prague hardfork includes both EIP-2028 and EIP-7623 at the same time. The Abstract sounded like we don't obey EIP-2028, so this PR clarifies.
- We did skip EIP-2028 in the previous hardforks, but it is more meaningful to mention that we comply with both 2028 and 7623.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you proposed and what alternatives you …

[KIP-223] Update description
